### PR TITLE
Add server to share duty with Novus bonus

### PR DESCRIPTION
**Pull request by Hiroa**
### Feature
 * Add client side to communicate with [ZodiacBuddyDB](https://github.com/Hiroa/ZodiacBuddyDB) (Hope the name is not a problem)
 * Move the "playSound" function to a separate class
 * Change the way that the duty light bonus is reset (every even UTC hours)

The server is hosted on [Fly.io](https://fly.io/) with the free plan for now.  
The communication are verified by jwt so a SECRETS_CS is needed on the repo secrets with the same key than the server.

### CODE REVIEW

**Comment by daemitus** [comment]
do we know if only a single zone can be on bonus at once?

**Comment by daemitus** [comment]
you can DM me the secret stuff on discord if you like: `daemitus#0941`

**Comment by daemitus** [comment]
lastly, `new HMACSHA512Algorithm()` says obsolete. Are we limited to using it via the fly.dev server or can we upgrade to something else?

**Comment by Hiroa** [comment]
> do we know if only a single zone can be on bonus at once?  

I don't know this information, same for the datacenter, I don't know if the bonus is the same between them. So I suppose not for now and will see when I got some data from the server. I admit that I never think of the first point and always assume that there is only one bonus at the time.

> lastly, `new HMACSHA512Algorithm()` says obsolete. Are we limited to using it via the fly.dev server or can we upgrade to something else?

All the security part is handle by the application, Fly.io only manage the server and https part. So we are free to use the algorithm that we want.  
I know that HashMac is deprecated but it do it's job on low security app and is easier to handle. But I can look to switch to RS512 or more.

**Pull request merged**
